
name: 'de_sandbox_dbt'
version: '1.0.0'
config-version: 2

profile: 'de_sandbox'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  de_sandbox_dbt:
      staging:
        materialized: view
