name: "dbt Blast Radius CI"
on:
  pull_request:
    branches: ["main"]

jobs:
  parallax_check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt & Parse Manifest
        working-directory: de_projects/airflow_sandbox/dbt_project
        run: |
          pip install dbt-core dbt-postgres
          dbt parse --profiles-dir .

      - name: Run Parallax Blast Radius CI
        uses: Ramprasad273/parallax@main
        with:
          manifest: "de_projects/airflow_sandbox/dbt_project/target/manifest.json"
          dialect: "postgres"
          fail_on: "CRITICAL"
          github_token: ${{ secrets.GITHUB_TOKEN }}
