name: "dbt Blast Radius CI"

on:
  pull_request:
    branches: ["main", "master"]

jobs:
  parallax_gate:
    name: "Parallax Blast Radius Gate"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    # Spins up a local Postgres instance in 3 seconds for dbt to connect to
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt & Compile Manifest
        run: |
          pip install dbt-core dbt-postgres
          cd de_projects/airflow_sandbox/dbt_project
          dbt compile || dbt parse

      - name: Run Parallax Blast Radius CI
        uses: Ramprasad273/parallax@main
        with:
          manifest: "de_projects/airflow_sandbox/dbt_project/target/manifest.json"
          fail_on: "HIGH"
          github_token: ${{ secrets.GITHUB_TOKEN }}
